databases:
  - name: WebsiteDB
    plan: free
    databaseName: selsayed
    user: selsayed
  
services:
  - type: web
    plan: free
    name: selsayed
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn website.asgi:application -k uvicorn.workers.UvicornWorker"
    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: WebsiteDB
          property: connectionString
      
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
